### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Darelllf** [SociallyIneptWeeb/AICoverGen#62]
i got this error when generate

i use macbook to run this code

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/Caskroom/miniforge/base/envs/kita/lib/python3.9/site-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/Users/darelllegoferdanu/Documents/AIART/AICoverGen-main/src/main.py", line 316, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "/Users/darelllegoferdanu/Documents/AIART/AICoverGen-main/src/main.py", line 83, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: 'Torch not compiled with CUDA enabled'

**Comment by flexobrain** [comment]
This might mean a version missmatch between your Torch and your CUDA versions.
You might need to install the right cuda toolkit.

Can you tell me (if you haven't found a solution or given up yet) if the Console returns true when typing in these commands?
`python3`
`>>> import torch`
`>>> torch.cuda.is_available()`
True (this should be what it returns. if it does not we have to look into it)

**Comment by flexobrain** [comment]
i am sleepy as fuck imma tell you first thing in the morning tomorow

**Comment by flexobrain** [comment]
you can try playing around with different torch and cuda versions. there are many solutions online but it took some playing around to find it for me. use the pip wheels for installing. you can google: torch doesn’t recognise cuda and will find plenty help. I will help further tomorrow but its late here in europe. goodnight.

**Comment by flexobrain** [comment]
the cuda version 11.8 is what you need for aicovergen. try to find a fitting torch version for it.

**Comment by flexobrain** [comment]
Hey how's it going? Were the fast tipps enough? Or is further assistance needed?

**Comment by Seanc26** [comment]
> Hey how's it going? Were the fast tipps enough? Or is further assistance needed?

Can I not use the current version of CUDA with AIcoverGen? I am using 12.3, I was under the impression pytorch was bundled in?
I am getting the error too btw

**Comment by flexobrain** [comment]
hey under my impression cuda 12.3 doesnt even work with this project because onnxruntime doesn’t really support it dot try to use 11.8 cuda and finding a torch version for it. There are documentations online. use the commands I gave earlier to try to see if torch accepts this cuda version. you may have to restart the Linux environment for the new cuda version to function. search online for the purge function to delete the current cuda version. tell me if you need further assistance. Good luck your fellow github user. sorry for the unstructured text lmao.

**Comment by flexobrain** [comment]
I also didn’t see if torch was bundled into the newest cuda version I just manually installed cuda and made it work with torch. like already mentioned, I just tried around I don’t really know how I got it to work lmao.
