### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by Awksys** [SociallyIneptWeeb/AICoverGen#7]
Hi,
I have trouble installing fairseq, I often get this type of error:

`Collecting omegaconf<2.1 (from fairseq)
  Downloading omegaconf-2.0.6-py3-none-any.whl (36 kB)
Collecting antlr4-python3-runtime==4.8 (from hydra-core<1.1,>=1.0.7->fairseq)
  Downloading antlr4-python3-runtime-4.8.tar.gz (112 kB)
     ---------------------------------------- 112.4/112.4 kB 6.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in C:\Users\...\Local\Temp\pip-pip-egg-info-of2_fg80`

Anyone has an idea ?

**Comment by Awksys** [comment]
Okay I think I fixed it, fairseq is now installed ! (I downgraded python to 3.8 and installed fairseq 0.10.0)

But now when I run main.py, after downloading the song file, it raises :

`EP Error D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=1738712584 ; hostname=LAPTOP-PAICUFA0 ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=238 ; expr=cudaSetDevice(info_.device_id); `

It's probably because I don't have any CUDA installed, but in this case is it possible to run the code anyway ?

**Comment by SociallyIneptWeeb** [comment]
You need to ensure that your driver version matches or exceeds your CUDA Toolkit version.

For 2.3 you need a 190.x driver, for 3.0 you need 195.x and for 3.1 you need 256.x (actually anything up to the next multiple of five is ok, e.g. 258.x for 3.1).

You can check your driver version by either running the deviceQueryDrv SDK sample or go into the NVIDIA Control Panel and choose System Information.

Download an updated driver from [www.nvidia.com/drivers](http://www.nvidia.com/drivers).

From stackoverflow https://stackoverflow.com/questions/3253257/cuda-driver-version-is-insufficient-for-cuda-runtime-version

**Comment by Awksys** [comment]
Thanks for your reply @SociallyIneptWeeb but actually I don't think I have any "NVIDIA product", is it still possible to get the driver ?

**Comment by SociallyIneptWeeb** [comment]
If you don't have an Nvidia GPU, you won't be able to run this locally, so you should use the colab notebook.

**Comment by Awksys** [comment]
Sad... Just spent so many hours to fix that fairseq install issue ;( 
Do you think there is another solution available to run it locally ?

**Comment by SociallyIneptWeeb** [comment]
For now, there isn't. Most AI models are only compatible with Nvidia GPUs.
