### ISSUE TITLE
ONNXRuntimeError

### ISSUE THREAD

**Issue by 300f20t** [SociallyIneptWeeb/AICoverGen#70]
Error
"[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running FusedConv node. Name:'Conv_33' Status Message: D:\\a\\_work\\1\\s\\onnxruntime\\core\\providers\\cuda\\cuda_call.cc:121 onnxruntime::CudaCall D:\\a\\_work\\1\\s\\onnxruntime\\core\\providers\\cuda\\cuda_call.cc:114 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-2UFN7CH ; file=D:\\a\\_work\\1\\s\\onnxruntime\\core\\providers\\cuda\\cuda_allocator.cc ; line=47 ; expr=cudaMalloc((void**)&p, size); \n\n"

All dependencies are installed correctly and the correct language models and audio file are used. At least that's what I think.

**Comment by KominoStyle** [comment]
You've encountered error code 6 in ONNX Runtime, specifically "RUNTIME_EXCEPTION," with a message indicating a CUDA failure 2: "out of memory" on your GPU. This error signifies that your GPU has insufficient memory available to complete the operation. To resolve this issue, you should consider allocating more memory to your GPU.

**Comment by 300f20t** [comment]
How can I change the amount of memory allocated by this program?

**Comment by 300f20t** [comment]
I'm sorry, I misunderstood you, the problem is solved...
